version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: taskmanager_db
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanager_network

  # Backend FastAPI
  backend:
    build:
      context: ./taskmanager_api  
      dockerfile: Dockerfile
    container_name: taskmanager_backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - taskmanager_network
    volumes:
      - ./taskmanager_api:/app  

  # Frontend React
  frontend:
    build:
      context: ./front_tm
      dockerfile: Dockerfile  # ← исправлено
    container_name: taskmanager_frontend
    ports:
      - "3000:80"  # ← или :80 для production
    depends_on:
      - backend
    networks:
      - taskmanager_network
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}

volumes:
  postgres_data:

networks:
  taskmanager_network:
    driver: bridge
